### ISSUE TITLE
[PRE REVIEW] A Sensitivity Analysis of a Regression Model of Ocean Temperature

### ISSUE THREAD

**Issue by acocac** [alan-turing-institute/environmental-ds-book#170]
# Notebook Pre-Review

**Submitting author:** @garimamalhotra @jedpe @dapivei

**Repository:** https://github.com/eds-book-gallery/repro-challenge-team-3

**Paper:** https://doi.org/10.1017/eds.2022.10

**Editor:** @annefou

**Reviewer:** @christopheredsall @oscarbau

**Managing EiC:** @acocac

## Status

**Author instructions**

Thanks for submitting your notebook to EDS book. 

**Editor instructions**

Thank you for considering managing the review workflow of a notebook submission to EDS book.

Please find and assign reviewers and start the main review.

**Comment by acocac** [comment]
@annefou thanks for confirming your availability to moderate the discussion for this submission, may I ask if you can assign reviewers and confirm their availability?

**Comment by annefou** [comment]
Hi @RachelFurner @christopheredsall @oscarbau — you volunteered to review for the CI2023 Reproducibility Challenge co-hosted by EDS book, Climate Informatics and Cambridge University Press and Assessment. Could you take a look at this submission and let us know if you might be able to volunteer a review for us?

**Comment by christopheredsall** [comment]
> Could you take a look at this submission and let us know if you might be able to volunteer a review for us? Thanks!

Sure, I can do that.

**Comment by oscarbau** [comment]
> Hi @RachelFurner @christopheredsall @oscarbau — you volunteered to review for the CI2023 Reproducibility Challenge co-hosted by EDS book, Climate Informatics and Cambridge University Press and Assessment. Could you take a look at this submission and let us know if you might be able to volunteer a review for us? Thanks!

Accepted :)

**Comment by acocac** [comment]
@RachelFurner already approved and express availability to review the submission this week in previous e-mail sent by Andrew Hyde (Cambridge University Press and Assessment). She's as the main author of the paper. I'll close the issue to start the review.

**Comment by RachelFurner** [comment]
Sorry for slow reply! As Alejandro says I'm happy to review this
