### ISSUE TITLE
[PRE REVIEW] Detection and attribution of climate change: A deep learning and variational approach

### ISSUE THREAD

**Issue by acocac** [alan-turing-institute/environmental-ds-book#171]
# Notebook Pre-Review

**Submitting author:** @ancazugo @SkirOwen @viktordomazetoski

**Repository:** https://github.com/eds-book-gallery/CI2023-RC-team2

**Paper:** https://doi.org/10.1017/eds.2022.17

**Editor:** @ampersandmcd

**Reviewer:** @asthanameghna

**Managing EiC:** @acocac

## Status

**Author instructions**

Thanks for submitting your notebook to EDS book. 

**Editor instructions**

Thank you for considering managing the review workflow of a notebook submission to EDS book.

Please find and assign reviewers and start the main review.

**Comment by acocac** [comment]
@ampersandmcd thanks for confirming your availability to moderate the discussion for this submission, may I ask if you can assign reviewers and confirm their availability?

**Comment by acocac** [comment]
Hi @asthanameghna @NHomer-Edi @dbhatedin — you volunteered to review for the CI2023 Reproducibility Challenge co-hosted by EDS book, Climate Informatics and Cambridge University Press and Assessment. Could you take a look at this submission and let us know if you might be able to volunteer a review for us? Thanks!

**Comment by asthanameghna** [comment]
I can take it up

**Comment by NHomer-Edi** [comment]
I am happy to review - it looks like a very interesting paper!

**Comment by dbhatedin** [comment]
Yes, glad to review, the topic is so impactful.

**Comment by acocac** [comment]
Closing as all reviewers confirm their availability.
