### ISSUE TITLE
[PRE REVIEW] Variational data assimilation with deep prior

### ISSUE THREAD

**Issue by acocac** [alan-turing-institute/environmental-ds-book#177]
# Notebook Pre-Review

**Submitting author:** @Mukulikaa @Rutika-16

**Repository:** https://github.com/eds-book-gallery/reproduce-deep-prior-4Dvar

**Paper:** https://doi.org/10.1017/eds.2022.31

**Editor:** @acocac

**Reviewer:** @crlna16 @tinaok

**Managing EiC:** @acocac

## Status

**Author instructions**

Thanks for submitting your notebook to EDS book. 

**Editor instructions**

Thank you for considering managing the review workflow of a notebook submission to EDS book.

Please find and assign reviewers and start the main review.

**Comment by acocac** [comment]
Hi @crlna16 @polpel @tinaok — you volunteered to review for the CI2023 Reproducibility Challenge co-hosted by EDS book, Climate Informatics and Cambridge University Press and Assessment. Could you take a look at this submission and let us know if you might be able to volunteer a review for us? Thanks!

**Comment by crlna16** [comment]
Hi @acocac , I am available to review

**Comment by tinaok** [comment]
Hi @acocac I’m available for the review too
