### ISSUE TITLE
[PRE REVIEW] Sea ice forecasting using the IceNet library

### ISSUE THREAD

**Issue by acocac** [alan-turing-institute/environmental-ds-book#236]
# Notebook Pre-Review

**Submitting author:** @bnubald 

**Repository:** https://github.com/eds-book-gallery/67a1e320-7c47-4ea9-8df8-e868326bc90b

**Notebook idea issue:** #221 

**Editor:** @annefou
**Reviewer:** @weiji14 @William-gregory

**Managing EiC:** @acocac

## Status

**Author instructions**

Thanks for submitting your notebook to EDS book. 

@bnubald if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @).

**Editor instructions**

Thank you for considering managing the review workflow of a notebook submission to EDS book.

Please find and assign reviewers and start the main review.

**Comment by acocac** [comment]
### Repository report:
The report below counts blank lines, comment lines, and physical lines of source code files using [cloc](https://github.com/AlDanial/cloc). It was generated according to the [latest commit](https://github.com/eds-book-gallery/67a1e320-7c47-4ea9-8df8-e868326bc90b/commit/0e5c45be7173379d8e17b46a27faf06d5967cde6) of the main branch from the target repository.

Potential reviewers and authors feel free this info only for informative purposes. We will generate a similar report after the review process.

```
github.com/AlDanial/cloc v 2.00  T=0.46 s (19.5 files/s, 18277.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                             6             22             28            465
Jupyter Notebook                 1              0           7743            143
Markdown                         1              2              0              9
JSON                             1              0              0              5
-------------------------------------------------------------------------------
SUM:                             9             24           7771            622
-------------------------------------------------------------------------------
```

**Comment by acocac** [comment]
👋 @DaniJonesOcean @JessicaS11 @weiji14 - would any of you be willing to review this submission for EDS book? We carry out our checklist-driven reviews in GitHub issues and follow these guidelines: https://edsbook.org/publishing/guidelines/guidelines-reviewers. We aim for reviews to be completed within about 2-4 weeks.

Thanks! 🙏

Title: "Sea ice forecasting using the IceNet library" [View the notebook with cell outputs](https://github.com/eds-book-gallery/67a1e320-7c47-4ea9-8df8-e868326bc90b/blob/main/notebook.ipynb) 📄 👈

**Comment by weiji14** [comment]
I'll be busy over the next couple of week until about 18 April (have a conference to prepare for), but can try to review this by around late April if that's ok.

**Comment by bnubald** [comment]
Thanks @acocac, happy to go with suggested reviewers!

**Comment by acocac** [comment]
> I'll be busy over the next couple of weeks until about 18 April (have a conference to prepare for), but can try to review this by around late April if that's ok.

@weiji14 thanks for indicating your interest and availability. I think late April should be fine. Let's wait for the responses of other potential reviewers. I'll tag you in mid-April in case we require your help on this 🙏

**Comment by weiji14** [comment]
Can I raise a concern on a potential conflict of interest? @acocac, I see that you as editor are affiliated with the Alan Turing institute, which the IceNet paper seems to have links to (on https://icenet.ai, it says IceNet is developed by BAS and the Alan Turing Institute). May I request the editor-in-chief (also @acocac it seems) to assign a different editor to review this EDS book?

**Comment by acocac** [comment]
@annefou thanks for confirming your availability to moderate the discussion for this submission, may I ask if you can contact potential reviewers and confirm their availability?

**Comment by acocac** [comment]
> Can I raise a concern on a potential conflict of interest? @acocac, I see that you as editor are affiliated with the Alan Turing institute, which the IceNet paper seems to have links to (on https://icenet.ai, it says IceNet is developed by BAS and the Alan Turing Institute). May I request the editor-in-chief (also @acocac it seems) to assign a different editor for handling the reviews of this EDS book?

@weiji14 thanks for raising the conflict of interest. Following your suggestion and transparency principles indicated in the EDS book [FAQ](https://edsbook.org/publishing/faq#conflict-of-interest), I've assigned a new editor, @annefou. Please note that the EDS book has a very limited capacity. We're working on recruiting volunteers to the editorial board from the pool of authors or reviewers. Feedback on the guidelines or publishing processes would be welcome!

**Comment by DaniJonesOcean** [comment]
@acocac and @annefou, I'm happy to serve as a reviewer if it's helpful. I should be able to get this done by late April.

**Comment by DaniJonesOcean** [comment]
That being said, as @weiji14 has pointed out for others, there may be a conflict of interest here too (I worked with Tom and others at BAS during my time there, and I am a co-author on the IceNet paper). @annefou, please advise :)

**Comment by weiji14** [comment]
Yes, the Cryosphere community is very 'small' :laughing: But that doesn't excuse us from not declaring any conflicts of interest that might undermine the credibility of the review process. We should set ourselves to a higher standard if we want scientific software libraries and written documentation (like Jupyter Books) to be recognized as credible scientific outputs (but I'm going off on a tangent here).

I will note that I have co-authored a JOSS paper with @JessicaS11, so we shouldn't both review this IceNet library together if following [Tier 3: Independent peer review](https://www.pnas.org/author-center/editorial-and-journal-policies) according to EDS's book FAQ.

**Comment by annefou** [comment]
@DaniJonesOcean About the potential Conflict of Interest (COI): it seems that the submitted notebook show a derivative work from IceNet (daily forecasting) which, as far as we understand, you were not directly involved in. Plus, the original IceNet paper you co-authored was published about 3 years ago.

Given this, I would like to ask you if you think you would be able to do an impartial assessment of this work and  then we could waive the conflict. However, we should just make sure this decision is properly recorded to maintain transparency.

We suggest we align with the COI guidelines outlined by JOSS/JOSE for this. You can check their policy here: [JOSS COI Policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy).

What do you think?

**Comment by annefou** [comment]
@bnubald just wanted to check, do you have any potential reviewers in mind who don't carry a conflict of interest? Let us know!

**Comment by JessicaS11** [comment]
Thanks for the invitation. Unfortunately, I'm not able to review this submission, as I'm currently working on multiple JOSS reviews. @mollymwieringa may be interested in reviewing (or know someone who is).

**Comment by annefou** [comment]
Based on this thread, discussion/clarification on potential COI, I believe @DaniJonesOcean and @weiji14  could review the notebook. Could you @DaniJonesOcean and @weiji14 confirm that you are happy to conduct the review?

**Comment by bnubald** [comment]
> @bnubald just wanted to check, do you have any potential reviewers in mind who don't carry a conflict of interest? Let us know!

Hi Anne, if COI still an issue, I did get a potential yes from following via an intermediary last week, though I do not have their github handle, just email:

https://research.ibm.com/people/geoffrey-dawson

**Comment by bnubald** [comment]
@annefou I've reached out to [William](https://william-gregory.github.io/) who's agreed ([GitHub profile](https://github.com/William-Gregory)).

**Comment by annefou** [comment]
Hi @William-gregory I understand that you would be happy to review this notebook. We would be very grateful if you could confirm?

**Comment by William-gregory** [comment]
Hi @annefou, yes I'm happy to review this notebook

**Comment by acocac** [comment]
Closing as all reviewers confirm their availability.
