### ISSUE TITLE
[PRE REVIEW] Livestock detection using DeepForest

### ISSUE THREAD

**Issue by acocac** [alan-turing-institute/environmental-ds-book#259]
# Notebook Pre-Review

**Submitting author:** @camappel

**Repository:** https://github.com/eds-book-gallery/95199651-9e81-4cae-a3a7-66398a9a5f62

**Notebook idea issue:** #257 

**Editor:** @acocac

**Reviewer:** @ethanwhite @louisavz

**Managing EiC:** @acocac 

## Status

**Author instructions**

Thanks for submitting your notebook to EDS book. 

@camappel if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @).

**Editor instructions**

Thank you for considering managing the review workflow of a notebook submission to EDS book.

Please find and assign reviewers and start the main review.
```

**Comment by acocac** [comment]
### Repository report:
The report below counts blank lines, comment lines, and physical lines of source code files using [cloc](https://github.com/AlDanial/cloc). It was generated according to the [latest commit](https://github.com/eds-book-gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/commit/f25f3b0dd997f052eea29da1f3ef694d105a8f44) of the main branch from the target repository.

Potential reviewers and authors feel free this info only for informative purposes. We will generate a similar report after the review process.

```
github.com/AlDanial/cloc v 2.00  T=0.07 s (204.5 files/s, 16373.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
YAML                             6             22             28            234
XML                              5              0              0            155
Jupyter Notebook                 1              0            518            101
Markdown                         1             13              0             45
JSON                             1              0              0              5
-------------------------------------------------------------------------------
SUM:                            14             35            546            540
-------------------------------------------------------------------------------
```

**Comment by acocac** [comment]
👋 @bw4sz @henrykironde @ethanwhite @louisavz - would any of you be willing to review this submission for EDS book? 

Title: "Livestock detection using DeepForest" [View the notebook with cell outputs](https://github.com/eds-book-gallery/95199651-9e81-4cae-a3a7-66398a9a5f62/blob/main/notebook.ipynb) 📄 👈

We carry out our checklist-driven reviews in GitHub issues and follow these guidelines: https://edsbook.org/publishing/guidelines/guidelines-reviewers. We aim for reviews to be completed within about 2-4 weeks.

Thanks! 🙏

**Comment by ethanwhite** [comment]
I can review this. I owe @camappel some responses related to this over in our repo anyway.

**Comment by louisavz** [comment]
Hi @acocac, I'm happy to review this also.

**Comment by acocac** [comment]
@louisavz @ethanwhite thanks for the quick and positive responses to review the submission. You'll have further instructions in a REVIEW issue in which you both will be tagged. Thank you!

**Comment by acocac** [comment]
Closing as all reviewers confirm their availability.

**Comment by camappel** [comment]
Hi all, thank you very much @ethanwhite @louisavz for agreeing to review my submission. I'm looking forward to your suggestions on improvements!
