### ISSUE TITLE
[NBI] Long timeseries phenology using Landsat data

### ISSUE THREAD

**Issue by ricardobarroslourenco** [alan-turing-institute/environmental-ds-book#52]
## What is the notebook about?

Landsat data is probably the longest standardized timeseries of remotely sensed data for land use. Plant phenology is an important proxy for climate change effects. Using long time series of RS data, would allow to see long-term trends, such as drifts on Start-of-season (SOS) and End-of-season (EOS) dates over decades, and how this occurs in the globe.

A secondary goal of the notebook would be how to pull out Landsat data and work on longer time-scales.  

- Landsat datasets are available at Google STAC repository : https://gee.stac.cloud/?cp=1&t=catalogs
- This would be loosely inspired on NASA ARSET training on Phenology: https://appliedsciences.nasa.gov/join-mission/training/english/arset-understanding-phenology-remote-sensing
- We would use some concepts of Pangeo as a stack: 
   - Using STAC endpoints of repositories;
   - Using intake as an ETL/Exploratory tool;
   -  Using Rasterio for Viz.
## Data Science Component

- [X] Sensor visualisation
- [ ] Preprocessing
- [ ] Modelling
- [ ] Post-processing
- [ ] Other: 

## Checklist:

- [X] Input data, pipeline and/or model are public with license/citation
- [X] The proposed notebook reuses existing codebase
- [X] The proposed notebook uses open-source packages
- [X] The proposed notebook is associated to existing publication(s)

**Comment by acocac** [comment]
@ricardobarroslourenco the notebook idea looks good to me. Do you have any geographical extent and/or environmental system in mind? My suggestion is to look for AOIs of your current work. Let me know if you find difficulties to continue the contribution process as it's detailed in the [preparation section.](https://the-environmental-ds-book.netlify.app/community/guidelines/guidelines-submission.html#preparation).

**Comment by ricardobarroslourenco** [comment]
I think I will probably start with a small area, such as the Ontario province here in Canada, to avoid needing to scale out (too much) processing for this data. 

I am currently debugging a Pangeo notebook (related to this issue here: https://github.com/pangeo-data/landsat-8-tutorial-gallery/issues/6 ), and once get that done, probably I will advance towards this implementation.

**Comment by acocac** [comment]
Great - it's good to start with a small area you feel comfortable with. It's amazing you're debugging existing Pangeo notebooks and even better asking support from the notebook authors! The Landsat demonstrator in the Pangeo Gallery is cool one using STAC endpoints. Looking forward to help when your first draft is ready 🌎 .

**Comment by acocac** [comment]
👋 @mfbenitezp I'm wondered if do you still consider to publishing the notebook idea described above?

**Comment by acocac** [comment]
👋 @ricardobarroslourenco I'm wondered if do you still consider to publishing the notebook idea described above?

**Comment by ricardobarroslourenco** [comment]
Hi @acocac ! Be happy to work on it (thanks for the reminder). I will put it on my calendar, and start developing.

**Comment by acocac** [comment]
> Hi @acocac ! Be happy to work on it (thanks for the reminder). I will put it on my calendar, and start developing.

Great - thanks @ricardobarroslourenco, you're welcome to try the recent release of EDS book, which contains improved guidelines, and also support to host large datasets as we've learnt from the Reproducibility Challenge!

**Comment by acocac** [comment]
@ricardobarroslourenco, may I ask if you're still considering to submit the notebook to EDS book, if not, would it be ok if I close the issue?

**Comment by ricardobarroslourenco** [comment]
Hi @acocac ! Please close this one. I have moved from this research on phenology. Once I finish my current one on greening, then I will ping you to start a new one. Sorry for the annoyance.

**Comment by acocac** [comment]
@ricardobarroslourenco thanks for the reply. I understand - Please feel free to open a new notebook idea once you're ready.
Thank you!
