### ISSUE TITLE
[NBI] Concatenating a gridded rainfall dataset into a time series

### ISSUE THREAD

**Issue by timo0thy** [alan-turing-institute/environmental-ds-book#53]
## What is the notebook about?

Calculate dry season rainfall averages in Borneo based on a gridded dataset and create a time series 

## Data Science Component

- [ ] Sensor visualisation
- [x] Preprocessing
- [ ] Modelling
- [ ] Post-processing
- [ ] Other: 

## Checklist:

- [x] Input data, pipeline and/or model are public with license/citation
- [x] The proposed notebook reuses existing codebase
- [x] The proposed notebook uses open-source packages
- [x] The proposed notebook is associated to existing publication(s)

## Additional information 

Source of data: https://psl.noaa.gov/data/gridded/data.ncep.reanalysis.html
Publication: https://journals.ametsoc.org/view/journals/bams/102/12/BAMS-D-20-0117.1.xml

Steps are as follows:
1. Load gridded rainfall dataset
2. Create seasonal means
3. Extract the study region
4. Create area-averaged time series
5. Extract the dry season and restrict to the study timeframe
6. Plot the time series

**Comment by acocac** [comment]
@timo0thy thanks for logging the notebook idea! The steps look good to me (: Do you think you can demonstrated them over the whole Borneo? or maybe you need to think a subset? 

Let me know if you find difficulties to continue the contribution process as it is detailed in the [preparation section](https://the-environmental-ds-book.netlify.app/community/guidelines/guidelines-submission.html#preparation).

**Comment by acocac** [comment]
@timo0thy forked the notebook template from the EnvDS book organisation, [here's the link](https://github.com/timo0thy/wildfires-preprocessing-timeseries) to the notebook which passed the GH action.
