### ISSUE TITLE
[NBI] Nutrientscape mapping in optically shallow tropical coastal waters

### ISSUE THREAD

**Issue by pirtapalola** [alan-turing-institute/environmental-ds-book#54]
## What is the notebook about?

Mapping nutrient flows in coastal waters using remotely-sensed multispectral data

Sentinel-2, https://scihub.copernicus.eu/
intake, xarray, hvplot, numpy

## Data Science Component

- [ ] Sensor visualisation
- [ ] Preprocessing
- [x] Modelling
- [ ] Post-processing
- [ ] Other: 

## Checklist:

- [x] Input data, pipeline and/or model are public with license/citation
- [ ] The proposed notebook reuses existing codebase
- [x] The proposed notebook uses open-source packages
- [ ] The proposed notebook is associated to existing publication(s)

**Comment by acocac** [comment]
Check this library, https://awesome-ee-spectral-indices.readthedocs.io/en/latest/list.html

**Comment by acocac** [comment]
Thanks @pirtapalola for the update. Feel free to open new notebook ideas in the future. Closing the issue sounds ok for me.
